stages:
  - test
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

tests:
  stage: test

  image: registry.gitlab.com/tozd/docker/meteor-testing:ubuntu-bionic-1.6.1.4

  script:
    # TODO: We should replace this with "meteor npm ci" when we will have npm 5.7.0 or newer.
    - meteor npm install
    - meteor list
    - meteor npm run lint-ci
    - meteor npm run test-ci
    - meteor npm run cypress-ci

  artifacts:
    name: "reports-$CI_JOB_ID"
    when: always
    paths:
      - tests/reports
    reports:
      junit: tests/reports/*.xml

check_authors:
  stage: test

  image: alpine:3

  script:
   - apk add --no-cache git bash
   - ./.authors/check-authors.sh

check_commits:
  stage: test

  image: alpine:3

  variables:
    GIT_DEPTH: "0"

  script:
   - apk add --no-cache git
   # No merge marks in commits.
   - '! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep "^"'
