version: 2
jobs:
  build:
    docker:
      - image: tozd/meteor-testing:ubuntu-xenial
    environment:
      METEOR_ALLOW_SUPERUSER: true
      CIRCLE_TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: ./.circleci/authors/check-authors.sh
      - run:
          command: |
            # No merge marks in commits.
            ! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep '^'
      - run: meteor npm install
      - run: meteor npm run lint-ci
      - run: meteor npm run test-ci
      - run: meteor npm run cypress-ci
      - store_test_results:
          path: /tmp/test-reports
      - store_artifacts:
          path: tests/cypress/videos
      - store_artifacts:
          path: tests/cypress/screenshots
