version: 2
jobs:
  build:
    docker:
      - image: tozd/meteor-testing:ubuntu-xenial
    environment:
      METEOR_ALLOW_SUPERUSER: true
      CIRCLE_TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          command: |
            apt-get update -q -q
            apt-get --yes --force-yes install wget
            wget http://launchpadlibrarian.net/413897613/chromium-codecs-ffmpeg-extra_72.0.3626.121-0ubuntu0.16.04.1_amd64.deb
            wget http://launchpadlibrarian.net/413897611/chromium-browser_72.0.3626.121-0ubuntu0.16.04.1_amd64.deb
            wget http://launchpadlibrarian.net/413897612/chromium-chromedriver_72.0.3626.121-0ubuntu0.16.04.1_amd64.deb
            dpkg -i chromium-browser_72.0.3626.121-0ubuntu0.16.04.1_amd64.deb chromium-codecs-ffmpeg-extra_72.0.3626.121-0ubuntu0.16.04.1_amd64.deb chromium-chromedriver_72.0.3626.121-0ubuntu0.16.04.1_amd64.deb
            rm -f *.deb
      - run: ./.circleci/authors/check-authors.sh
      - run:
          command: |
            # No merge marks in commits.
            ! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep '^'
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-npm-{{ .Branch }}
            - v1-npm
      # TODO: We should replace this with "meteor npm ci" when we will have npm 5.7.0 or newer.
      - run: meteor npm install
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: meteor list
      - run: meteor npm run lint-ci
      - run: meteor npm run test-ci
      - run: meteor npm run cypress-ci
      - store_test_results:
          path: /tmp/test-reports
      - store_artifacts:
          path: tests/cypress/videos
      - store_artifacts:
          path: tests/cypress/screenshots
